### ISSUE TITLE
Properties in property file can't be resolved

### ISSUE THREAD

**Issue by MartinX3** [merapar/spring-boot-starter-graphql#29]
I copied the application.yaml
```yaml
com.merapar.graphql:
  rootQueryName: "queries"
  rootQueryDescription: ""
  rootMutationName: "mutations"
  rootMutationDescription: ""
  requestMapping:
    path: "/v1/graphql"
  executor:
    minimumThreadPoolSizeQuery: 10
    maximumThreadPoolSizeQuery: 20
    keepAliveTimeInSecondsQuery: 30
    minimumThreadPoolSizeMutation: 10
    maximumThreadPoolSizeMutation: 20
    keepAliveTimeInSecondsMutation: 30
    minimumThreadPoolSizeSubscription: 10
    maximumThreadPoolSizeSubscription: 20
    keepAliveTimeInSecondsSubscription: 30
```
I converted it to application.properties:
```properties
com.merapar.graphql.rootQueryName="queries"
com.merapar.graphql.rootQueryDescription=""
com.merapar.graphql.rootMutationName="mutations"
com.merapar.graphql.rootMutationDescription=""
com.merapar.graphql.requestMapping.path="/v1/graphql"
com.merapar.graphql.executor.minimumThreadPoolSizeQuery=10
com.merapar.graphql.executor.maximumThreadPoolSizeQuery=20
com.merapar.graphql.executor.keepAliveTimeInSecondsQuery=30
com.merapar.graphql.executor.minimumThreadPoolSizeMutation=10
com.merapar.graphql.executor.maximumThreadPoolSizeMutation=20
com.merapar.graphql.executor.keepAliveTimeInSecondsMutation=30
com.merapar.graphql.executor.minimumThreadPoolSizeSubscription=10
com.merapar.graphql.executor.maximumThreadPoolSizeSubscription=20
com.merapar.graphql.executor.keepAliveTimeInSecondsSubscription=30
```

For every line IntelliJ is telling me (example):
> Cannot resolve configuration property 'com.merapar.graphql.rootQueryName'

Edit:
Regardless of the warning, they get interpreted by the project.
Weird.
